=== MohamedSamirShabaan/JDBC-API/JDBC/sample/table_name1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT table (columns,rows)>
<!ELEMENT columns (column_name1,column_name2,column_name3)>
<!ELEMENT row (column_name1,column_name2,column_name3)>
<!ELEMENT rows (row*)>
<!ELEMENT column_name1 (#PCDATA)>
<!ELEMENT column_name2 (#PCDATA)>
<!ELEMENT column_name3 (#PCDATA)>

=== MohamedSamirShabaan/JDBC-API/JDBC/sample/table_name1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE table SYSTEM "table_name1.dtd">
<table><columns><column_name1>varchar</column_name1><column_name2>int</column_name2><column_name3>varchar</column_name3></columns><rows><row><column_name1>'11111111'</column_name1><column_name2>22222222</column_name2><column_name3>'333333333'</column_name3></row><row><column_name1>'11111111'</column_name1><column_name2>22222222</column_name2><column_name3>'333333333'</column_name3></row><row><column_name1>'value2'</column_name1><column_name2>5</column_name2><column_name3>'value4'</column_name3></row><row><column_name1>'value1'</column_name1><column_name2>6</column_name2><column_name3>'value3'</column_name3></row><row><column_name1>'value1'</column_name1><column_name2>4</column_name2><column_name3>'value3'</column_name3></row><row><column_name1>'value2'</column_name1><column_name2>5</column_name2><column_name3>'value4adfshfjgkhlgj'</column_name3></row><row><column_name1>'value2'</column_name1><column_name2>3</column_name2><column_name3>'value4'</column_name3></row></rows></table>
